New-AzVm `
    -ResourceGroupName 'rg-rfdemo-prod' `
    -Name 'vm-rfdemo-app01' `
    -Location 'eastus' `
    -Size 'Standard_B2ms' `
    -Image 'MicrosoftWindowsServer:WindowsServer:2022-datacenter-azure-edition:latest' `
    -VirtualNetworkName 'vnet-rfdemo-prod' `
    -SubnetName 'snet-rfdemo-app' `
    -SecurityGroupName 'nsg-rfdemo-app' `
    -PublicIpAddressName 'pip-rfdemo-app01' `
    -OpenPorts 80,443,3389